// Mefi's Studio AI+ — preload bridge (CJS; Electron's safe preload format).
const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("mefiStudio", {
  projectsList: () => ipcRenderer.invoke("projects:list"),
  projectsAdd: () => ipcRenderer.invoke("projects:add"),
  projectsSelect: (id) => ipcRenderer.invoke("projects:select", id),
  onProjects: (callback) => ipcRenderer.on("projects:changed", (_event, data) => callback(data)),
  readCatalog: () => ipcRenderer.invoke("catalog:read"),
  refreshCatalog: () => ipcRenderer.invoke("catalog:refresh"),
  launchStudio: () => ipcRenderer.invoke("studio:launch"),
  runSmoke: () => ipcRenderer.invoke("studio:smoke"),
  launchGame: () => ipcRenderer.invoke("studio:game"),
  stopStudio: () => ipcRenderer.invoke("studio:stop"),
  getApiKey: (which) => ipcRenderer.invoke("settings:get-key", which),
  setApiKey: (key, which) => ipcRenderer.invoke("settings:set-key", key, which),
  getAiRouting: () => ipcRenderer.invoke("settings:get-ai-routing"),
  setAiRouting: (patch) => ipcRenderer.invoke("settings:set-ai-routing", patch),
  jevStatus: () => ipcRenderer.invoke("jev:status"),
  jevProbe: () => ipcRenderer.invoke("jev:probe"),
  jevSetEnabled: (enabled) => ipcRenderer.invoke("jev:set-enabled", enabled),
  cliStatus: () => ipcRenderer.invoke("studio:cli-status"),
  launchCli: (id) => ipcRenderer.invoke("studio:launch-cli", id),
  testZai: () => ipcRenderer.invoke("studio:test-zai"),
  speedProbe: (modelId) => ipcRenderer.invoke("speed:probe", { modelId }),
  speedMeasurements: () => ipcRenderer.invoke("speed:measurements-read"),
  openExternal: (url) => ipcRenderer.invoke("shell:open", url),
  shellReveal: (filePath) => ipcRenderer.invoke("shell:reveal", filePath),
  shellCopy: (text) => ipcRenderer.invoke("shell:copy", text),
  eyesPickPng: () => ipcRenderer.invoke("eyes:pick-png"),
  eyesState: (sessionId) => ipcRenderer.invoke("eyes:state", { sessionId }),
  eyesChanges: (sessionId) => ipcRenderer.invoke("eyes:changes", { sessionId }),
  eyesTodos: () => ipcRenderer.invoke("eyes:todos"),
  eyesLog: (lines) => ipcRenderer.invoke("eyes:log", { lines }),
  eyesPinsRead: () => ipcRenderer.invoke("eyes:pins-read"),
  eyesPinsWrite: (pins) => ipcRenderer.invoke("eyes:pins-write", pins),
  eyesWatch: (running) => ipcRenderer.invoke("eyes:watch", { running }),
  eyesRequestsRead: () => ipcRenderer.invoke("eyes:requests-read"),
  eyesRequestsWrite: (requests) => ipcRenderer.invoke("eyes:requests-write", requests),
  eyesCheckpointsRead: () => ipcRenderer.invoke("eyes:checkpoints-read"),
  eyesBriefingRead: () => ipcRenderer.invoke("eyes:briefing-read"),
  eyesCollisions: () => ipcRenderer.invoke("eyes:collisions"),
  assistantRun: (mode, sessionId, payload) => ipcRenderer.invoke("assistant:run", { mode, sessionId, payload }),
  assistantProactive: (enabled, minutes) => ipcRenderer.invoke("assistant:proactive", { enabled, minutes }),
  assistantAutopilot: (prefs) => ipcRenderer.invoke("assistant:autopilot", prefs),
  assistantStatus: () => ipcRenderer.invoke("assistant:status"),
  assistantState: () => ipcRenderer.invoke("assistant:state"),
  assistantMessage: (text, projectId) => ipcRenderer.invoke("assistant:message", { text, projectId }),
  assistantWorkOn: (target) => ipcRenderer.invoke("assistant:work-on", target ?? {}),
  assistantFocus: (target) => ipcRenderer.invoke("assistant:focus", target ?? null),
  assistantNodeContext: (payload) => ipcRenderer.invoke("assistant:node-context", payload ?? {}),
  assistantControl: (action) => ipcRenderer.invoke("assistant:control", { action }),
  assistantPrefs: (patch) => ipcRenderer.invoke("assistant:prefs", patch),
  auditorRun: () => ipcRenderer.invoke("auditor:run"),
  checkpointAdd: (sessionId, note) => ipcRenderer.invoke("checkpoint:add", { sessionId, note }),
  analyzerRun: (kind, payload) => ipcRenderer.invoke("analyzer:run", { kind, ...payload }),
  analyzerPick: () => ipcRenderer.invoke("analyzer:pick"),
  analyzerAi: (kind, payload) => ipcRenderer.invoke("analyzer:ai", { kind, payload }),
  tasksList: () => ipcRenderer.invoke("tasks:list"),
  tasksCreate: (task) => ipcRenderer.invoke("tasks:create", task),
  tasksSave: (tasks) => ipcRenderer.invoke("tasks:save", tasks),
  ideasList: () => ipcRenderer.invoke("ideas:list"),
  ideasSave: (ideas) => ipcRenderer.invoke("ideas:save", ideas),
  ideasScan: (ai) => ipcRenderer.invoke("ideas:scan", { ai }),
  referenceGather: (payload) => ipcRenderer.invoke("reference:gather", payload),
  prefsGet: () => ipcRenderer.invoke("prefs:get"),
  prefsSet: (prefs) => ipcRenderer.invoke("prefs:set", prefs),
  updateStatus: () => ipcRenderer.invoke("update:status"),
  updateSet: (auto) => ipcRenderer.invoke("update:set", { auto }),
  updateApply: () => ipcRenderer.invoke("update:apply"),
  machineStatus: (kill) => ipcRenderer.invoke("machine:status", { kill: Boolean(kill) }),
  machineWatch: (running) => ipcRenderer.invoke("machine:watch", { running }),
  machineSet: (prefs) => ipcRenderer.invoke("machine:set", prefs),
  machineKill: (pid) => ipcRenderer.invoke("machine:kill", { pid }),
  onAssistantStatus: (callback) => ipcRenderer.on("assistant:status", (_event, status) => callback(status)),
  onMachineStatus: (callback) => ipcRenderer.on("machine:status", (_event, status) => callback(status)),
  onTasks: (callback) => ipcRenderer.on("eyes:tasks", (_event, tasks) => callback(tasks)),
  onIdeas: (callback) => ipcRenderer.on("eyes:ideas", (_event, ideas) => callback(ideas)),
  onRequests: (callback) => ipcRenderer.on("eyes:requests", (_event, requests) => callback(requests)),
  onCheckpoints: (callback) => ipcRenderer.on("eyes:checkpoints", (_event, data) => callback(data)),
  onBriefing: (callback) => ipcRenderer.on("eyes:briefing", (_event, data) => callback(data)),
  onEyesActivity: (callback) => ipcRenderer.on("eyes:activity", (_event, data) => callback(data)),
  onEyesError: (callback) => ipcRenderer.on("eyes:error", (_event, message) => callback(message)),
  onStudioLog: (callback) => ipcRenderer.on("studio:log", (_event, line) => callback(line)),
  onStudioExit: (callback) => ipcRenderer.on("studio:exit", (_event, info) => callback(info)),
  onUpdateEvent: (callback) => ipcRenderer.on("update:event", (_event, payload) => callback(payload)),
  onAssistant: (callback) => ipcRenderer.on("eyes:assistant", (_event, payload) => callback(payload)),
});
