import * as T from 'three';
import{RoundedBoxGeometry}from'three/addons/geometries/RoundedBoxGeometry.js';
import{RoomEnvironment}from'three/addons/environments/RoomEnvironment.js';
import{EffectComposer}from'three/addons/postprocessing/EffectComposer.js';
import{RenderPass}from'three/addons/postprocessing/RenderPass.js';
import{UnrealBloomPass}from'three/addons/postprocessing/UnrealBloomPass.js';
import{OutputPass}from'three/addons/postprocessing/OutputPass.js';
const kind=new URLSearchParams(location.search).get('kind')||'main',S=kind==='squares',P=kind==='constellation',W=innerWidth,H=innerHeight;
const theme=P?'portrait':S?'square':'wide';document.body.className=theme;
const scene=new T.Scene(),camera=new T.PerspectiveCamera(P?38:40,W/H,.1,150);
const r=new T.WebGLRenderer({antialias:true,alpha:false,preserveDrawingBuffer:true,powerPreference:'high-performance'});r.setPixelRatio(1);r.setSize(W,H);r.toneMapping=T.ACESFilmicToneMapping;r.toneMappingExposure=1.05;document.body.prepend(r.domElement);
const env=new RoomEnvironment(),pm=new T.PMREMGenerator(r);scene.environment=pm.fromScene(env,.07).texture;env.dispose();scene.environmentIntensity=.82;
const composer=new EffectComposer(r);composer.addPass(new RenderPass(scene,camera));composer.addPass(new UnrealBloomPass(new T.Vector2(W,H),S?.055:.09,.25,1.3));composer.addPass(new OutputPass());
const bg=document.createElement('canvas');bg.width=1024;bg.height=Math.round(1024*H/W);const b=bg.getContext('2d');b.fillStyle=S?'#e4eaf7':'#080d1d';b.fillRect(0,0,bg.width,bg.height);for(const[x,y,rad,c]of S?[[0,.2,.8,'#ebfaff'],[1,.7,.8,'#cdbcee'],[0,1,.6,'#a4ddea']]:[[.2,.8,.6,'#39305f'],[.85,.15,.65,'#104450'],[1,1,.5,'#392849']]){const g=b.createRadialGradient(x*bg.width,y*bg.height,0,x*bg.width,y*bg.height,rad*Math.max(bg.width,bg.height));g.addColorStop(0,c);g.addColorStop(1,'transparent');b.fillStyle=g;b.fillRect(0,0,bg.width,bg.height);}scene.background=new T.CanvasTexture(bg);scene.background.colorSpace=T.SRGBColorSpace;scene.fog=new T.FogExp2(S?0xcdddeb:0x0b1528,P?.012:.018);
scene.add(new T.HemisphereLight(0xb9e8ff,S?0xb1b2cd:0x242743,1.8));for(const[c,p,i]of[[0xd3ffed,[-8,15,8],2],[0xb99bff,[10,6,-9],2],[0xffffff,[0,20,0],1.3]]){const l=new T.DirectionalLight(c,i);l.position.set(...p);scene.add(l);}
const clamp=x=>Math.max(0,Math.min(1,x)),ease=x=>{x=clamp(x);return x*x*x*(x*(x*6-15)+10);},out=x=>1-Math.pow(1-clamp(x),3),mix=T.MathUtils.lerp,rng=i=>(Math.sin(i*71.7+4.1)*12347.31)%1;
const v=(x=0,y=0,z=0)=>new T.Vector3(x,y,z),root=new T.Group();scene.add(root);
const pearl=new T.MeshPhysicalMaterial({color:S?0xa9ccd7:0x849ab9,metalness:.86,roughness:.22,clearcoat:1,iridescence:.85,iridescenceIOR:1.4,iridescenceThicknessRange:[160,430]});
const ink=new T.MeshBasicMaterial({color:0x142333});
const glow=c=>new T.MeshStandardMaterial({color:c,emissive:c,emissiveIntensity:.72,metalness:.2,roughness:.32});const mint=glow(0x94efc9),lilac=glow(0xa291e8),cyan=glow(0x6fcde3);
const tileMaterials=[0x75bfae,0x859fde,0xb297d6,0xa1dacd,0x4c82aa].map(color=>new T.MeshPhysicalMaterial({color,roughness:.25,metalness:.52,iridescence:.4,clearcoat:.7}));
function box(w,h,d,mat=pearl,rad=.1,parent=root){const m=new T.Mesh(new RoundedBoxGeometry(w,h,d,3,rad),mat);parent.add(m);return m;}
function ball(size,mat=mint,parent=root){const m=new T.Mesh(new T.SphereGeometry(size,24,16),mat);parent.add(m);return m;}
function ring(radius,thick,mat=mint,parent=root){const m=new T.Mesh(new T.TorusGeometry(radius,thick,10,100),mat);parent.add(m);return m;}
function line(points,mat=mint,parent=root,width=.018){const curve=points instanceof T.Curve?points:new T.CatmullRomCurve3(points);const m=new T.Mesh(new T.TubeGeometry(curve,60,width,6,false),mat);m.userData.curve=curve;parent.add(m);return m;}
function label(text,w,h,color='#d4f9ee'){const c=document.createElement('canvas');c.width=768;c.height=192;const x=c.getContext('2d');x.font='600 77px "Segoe UI",sans-serif';x.fillStyle=color;x.textAlign='center';x.textBaseline='middle';x.fillText(text,384,96);const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;return new T.Mesh(new T.PlaneGeometry(w,h),new T.MeshBasicMaterial({map:tex,transparent:true,depthWrite:false,toneMapped:false}));}
function robot(parent,scale=1){const g=new T.Group();parent.add(g);box(1.3,1.22,.92,pearl,.26,g);const visor=box(1.02,.6,.1,ink,.15,g);visor.position.set(0,.07,.49);for(const x of[-.23,.23]){const eye=box(.065,.18,.025,mint,.025,g);eye.position.set(x,.08,.554);}for(const x of[-.73,.73]){const ear=box(.15,.36,.3,pearl,.07,g);ear.position.x=x;}const m=label('M+',.36,.11);m.position.set(0,-.43,.47);g.add(m);const orbit=ring(1.02,.023,mint,g);orbit.rotation.set(.8,.45,.2);const orbit2=ring(1.28,.013,lilac,g);orbit2.rotation.set(.1,1.4,.5);g.scale.setScalar(scale);return{g,orbit,orbit2};}
const hero=new T.Group();root.add(hero);const bot=robot(hero,1.45);bot.g.position.y=1.3;
const heroArcs=[];for(let i=0;i<3;i++){const a=ring(2.05+i*.33,i===1?.035:.065,i===1?cyan:pearl,hero);a.position.y=1.3;a.rotation.set(.35+i*.7,.5+i*.6,.3+i*.6);heroArcs.push(a);}
const heroTiles=[];for(let i=0;i<56;i++){const q=box(.42,.42,.42,tileMaterials[i%5],.06,hero);heroTiles.push(q);}
const info=[['map','See the whole project.','HOME · PLANS · PROJECT MAP'],['pipeline','Give work a direction.','AGENT BRAIN · PARALLEL STEPS'],['playbook','Keep what works.','PLAYBOOK · BRAIN MAPS'],['routing','Your models. Your call.','OPENROUTER · MODEL ROUTING'],['music','Stay in your flow.','MUSIC · RADIO · FLOATING VIDEO'],['tasks','Watch it come home.','REPORTS · REVIEW · CHECKS']];
const flatPositions=[[-10,0,-7],[1,0,-13],[12,0,-5],[11,0,9],[-1,0,14],[-12,0,7]];
const stations=info.map((a,i)=>{const g=new T.Group();root.add(g);if(P){const angle=-.7+i*1.05;g.position.set(Math.sin(angle)*4.2,i*4.8+6,Math.cos(angle)*4.2);}else if(S){g.position.set(i*11-25,Math.sin(i*.9)*1.2,-i*4);}else g.position.set(...flatPositions[i]);return{g,index:i,key:a[0],parts:[],pipes:[],lights:[],screen:null};});
// A map made from floating islands and file blocks.
{const s=stations[0];for(let z=0;z<3;z++)for(let x=0;x<3;x++){const g=new T.Group();s.g.add(g);g.position.set((x-1)*1.52,0,(z-1)*1.43);box(1.31,.23,1.12,tileMaterials[(x+z)%5],.07,g);for(let k=0;k<3;k++){const f=box(.22,.16+.06*k,.3,pearl,.035,g);f.position.set(-.33+k*.32,.24,-.05);}s.parts.push(g);if(x<2)s.pipes.push(line([v((x-1)*1.52,.07,(z-1)*1.43),v((x-.5)*1.52,.12,(z-1)*1.43),v(x*1.52,.07,(z-1)*1.43)],cyan,s.g,.013));}const orbit=ring(2.72,.025,mint,s.g);orbit.rotation.x=Math.PI/2;orbit.position.y=-.28;s.ring=orbit;}
// Agents split out along curved paths; reports return along the same paths.
{const s=stations[1];s.bot=robot(s.g,.8);s.bot.g.position.set(0,2,0);for(let i=0;i<6;i++){const a=i*Math.PI/3,p=v(Math.cos(a)*2.2,Math.sin(a*2)*.3,Math.sin(a)*1.55);const g=new T.Group();s.g.add(g);const orb=ball(.3,i%2?lilac:mint,g),band=ring(.41,.028,pearl,g);band.rotation.set(.3,a,.4);const curve=new T.CubicBezierCurve3(v(0,1.8,0),v(p.x*.4,1.4,p.z),v(p.x,.5,p.z),p);const beam=line(curve,i%2?lilac:cyan,s.g,.022);s.parts.push(g);s.pipes.push(beam);const light=ball(.072,mint,s.g);s.lights.push(light);}const base=ring(2.7,.027,pearl,s.g);base.rotation.x=Math.PI/2;s.ring=base;}
// Physical recipe books fan out, then settle into a shelf.
{const s=stations[2];for(let i=0;i<5;i++){const g=new T.Group();s.g.add(g);const cover=box(1.1,1.9,.31,tileMaterials[i],.08,g);const pages=box(.93,1.69,.34,new T.MeshStandardMaterial({color:0xd9e5ef,roughness:.6}),.025,g);pages.position.x=.05;const front=box(1.1,1.9,.04,tileMaterials[i],.04,g);front.position.z=.19;for(let k=0;k<3;k++){const bar=box(.62-k*.13,.035,.022,mint,.008,g);bar.position.set(-k*.06,.3-k*.22,.218);}g.userData.i=i;s.parts.push(g);}const shelf=box(5.8,.17,1.5,pearl,.08,s.g);shelf.position.y=-1.1;s.shelf=shelf;}
// Provider choices orbit a single routing hub.
{const s=stations[3];s.hub=box(.9,.9,.9,pearl,.17,s.g);s.hub.position.y=.6;const names=['OpenRouter','OpenAI','Anthropic','Local'];for(let i=0;i<4;i++){const group=new T.Group();s.g.add(group);ball(.42,tileMaterials[i],group);const band=ring(.57,.022,i%2?lilac:mint,group);band.rotation.x=Math.PI/2;const tag=label(names[i],1.6,.36,S?'#244b68':'#cce7ef');tag.position.y=-.77;group.add(tag);s.parts.push(group);}const orbit=ring(2.7,.025,cyan,s.g);orbit.rotation.x=Math.PI/2;s.ring=orbit;}
// A sculptural media waveform; its movement is designed for silent playback.
{const s=stations[4];for(let i=0;i<25;i++){const bar=box(.13,1,.2,tileMaterials[i%5],.06,s.g);bar.position.x=(i-12)*.205;s.parts.push(bar);}const disk=new T.Mesh(new T.CylinderGeometry(1.48,1.48,.12,70),pearl);disk.rotation.x=Math.PI/2;disk.position.set(0,.25,-.75);s.g.add(disk);s.disk=disk;const groove=ring(1.1,.014,lilac,s.g);groove.position.copy(disk.position);groove.position.z+=.08;s.ring=groove;ball(.14,mint,s.g).position.set(0,.25,-.64);}
// Evidence gathers into checkmarks, then flows back to the companion.
{const s=stations[5];for(let i=0;i<6;i++){const g=new T.Group();s.g.add(g);box(.9,.9,.32,tileMaterials[i%5],.14,g);line([v(-.24,0,.19),v(-.07,-.16,.19),v(.27,.22,.19)],mint,g,.047);g.userData.i=i;s.parts.push(g);}s.bot=robot(s.g,.75);s.bot.g.position.set(0,1.1,-1.3);}
// A real interface plane briefly meets the camera, without a surrounding caption card.
const crops={map:[245,95,1330,835],pipeline:[553,160,1030,558],playbook:[251,90,1330,820],routing:[265,115,1320,775],music:[950,85,635,870],tasks:[650,100,940,800]};
await document.fonts.ready;
if(!P)for(const s of stations){const im=await new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=reject;image.src=`../../dist/promo/screens/${s.key}.png`;});const c=document.createElement('canvas');c.width=1280;c.height=800;const x=c.getContext('2d');x.fillStyle='#111822';x.fillRect(0,0,1280,800);const[sx,sy,sw,sh]=crops[s.key],scale=Math.min(1280/sw,800/sh),dw=sw*scale,dh=sh*scale;x.drawImage(im,sx,sy,sw,sh,(1280-dw)/2,(800-dh)/2,dw,dh);const texture=new T.CanvasTexture(c);texture.colorSpace=T.SRGBColorSpace;texture.anisotropy=r.capabilities.getMaxAnisotropy();const g=new T.Group();s.g.add(g);const plane=new T.Mesh(new T.PlaneGeometry(4.7,2.94),new T.MeshBasicMaterial({map:texture,transparent:true,toneMapped:false,opacity:0}));g.add(plane);g.position.set(3.5,1.8,-1.6);g.rotation.y=-.22;s.screen={g,plane};}
// The connective thread is physical: camera moves along it, particles travel through it.
const trailPoints=[v(0,.25,0),...stations.map(s=>s.g.position.clone().add(v(0,.1,0)))];if(!P)trailPoints.push(v(0,.25,0));
const trailCurve=new T.CatmullRomCurve3(trailPoints),trail=line(trailCurve,cyan,root,.014),trailDots=[];for(let i=0;i<20;i++)trailDots.push(ball(.047,i%2?mint:lilac,root));
const floatBits=[];for(let i=0;i<70;i++){const p=ball(.015+Math.abs(rng(i))*.025,i%3?cyan:lilac,root);p.userData.base=v(rng(i+23)*38,P?Math.abs(rng(i+101))*40:rng(i+72)*10,rng(i+77)*32);floatBits.push(p);}
// Pearlescent blocks are the square film's connecting visual motif.
const floorTiles=[];if(S)for(let i=0;i<100;i++){const f=box(.63,.17,.63,tileMaterials[i%5],.06,root);f.userData={i};floorTiles.push(f);}
const title=document.querySelector('h1'),sub=document.querySelector('.sub'),url=document.querySelector('.url'),chapter=document.querySelector('.chapter'),counter=document.querySelector('.counter');
const starts=[2.7,6.5,10.3,14.1,17.9,21.7],ends=[6.5,10.3,14.1,17.9,21.7,25.5];let old='';
function words(t,index){const state=t<2.7?'hero':t>=25.5?'outro':'feature',age=state==='hero'?t:state==='outro'?t-25.5:t-starts[index],duration=state==='hero'?2.7:state==='outro'?4.5:3.8;
 if(old!==state+index){old=state+index;document.body.className=theme+' '+state;title.innerHTML=state==='hero'?(S?'One idea.<br>Infinite possibilities.':P?'A little spark.<br>A whole studio.':'It starts with an idea.'):state==='outro'?(P?'Your idea.<br>A whole studio.':'Your idea. A whole studio.'):info[index][1];sub.textContent=state==='hero'?'':state==='outro'?'MEFI’S STUDIO AI+ · FREE & OPEN SOURCE':info[index][2];url.textContent=state==='outro'?'github.com/nateecho32-stack/mefi-studio':'';counter.textContent=state==='feature'?String(index+1).padStart(2,'0')+' / 06':'';}
 const a=state==='outro'?out((age-.55)/.65):out((age-.55)/.5)*(1-ease((age-duration+.4)/.4));chapter.style.opacity=String(a);chapter.style.transform=`translateY(${(1-a)*12}px)`;
}
function update(t){const idx=t<2.7?-1:t>=25.5?6:Math.min(5,Math.floor((t-2.7)/3.8));words(t,Math.max(0,Math.min(5,idx)));
 bot.g.rotation.set(.1*Math.sin(t*.7),-.2+t*.08,.03*Math.sin(t));bot.orbit.rotation.z=t*.3;bot.orbit2.rotation.z=-t*.17;bot.g.position.y=1.3+Math.sin(t)*.1;heroArcs.forEach((o,i)=>o.rotation.z=t*.16*(i%2?-1:1)+i*.6);
 heroTiles.forEach((o,i)=>{const row=Math.floor(i/8),col=i%8,p=out((t-(row+col)*.035)/.85),a=i*.43+t*.14,rad=2.6+.3*Math.sin(i);if(S){o.position.set((col-3.5)*.5*(1-p)+Math.cos(a)*rad*p,1.1+(row-3)*.5*(1-p)+Math.sin(a)*rad*.6*p,Math.sin(a*.7)*2.4*p);o.rotation.set(t*.1+i,.3*i,t*.2);o.scale.setScalar(.85);}else{o.position.set(Math.cos(a)*rad,1.3+Math.sin(a)*1.7,Math.sin(a*.72)*1.8);o.rotation.set(i+t*.1,t*.25,i);o.scale.setScalar(.35);}o.visible=idx<0||idx===6;});
 for(const s of stations){const age=t-starts[s.index],p=out((age+.7)/1.15),active=idx===s.index;const local=age;
  if(s.index===0){s.parts.forEach((g,i)=>{g.position.y=.16*Math.sin(t*1.1+i*.5)+Math.sin(clamp((age+.4-i*.07)/.9)*Math.PI)*.5;g.rotation.y=Math.sin(t*.3)*.04;});s.ring.rotation.z=t*.05;}
  if(s.index===1){s.bot.g.rotation.y=Math.sin(t*.8)*.35;for(let i=0;i<6;i++){const q=out((local-.3-i*.13)/.7);const pos=s.pipes[i].userData.curve.getPoint(q);s.parts[i].position.copy(pos);s.parts[i].scale.setScalar(Math.max(.001,q));s.parts[i].rotation.y=t*.55+i;s.pipes[i].geometry.setDrawRange(0,Math.floor(s.pipes[i].geometry.index.count*q/6)*6);s.lights[i].position.copy(s.pipes[i].userData.curve.getPoint((t*.65+i*.15)%1));}}
  if(s.index===2){s.parts.forEach((g,i)=>{const wave=Math.sin(t*.8+i*.5);g.position.set((i-2)*1.05,.08+wave*.08,Math.sin(i*.7+local*.2)*.18);g.rotation.set(.02*wave,(i-2)*.09+Math.sin(local*.7)*.15,Math.sin(t*.4+i)*.025);});}
  if(s.index===3){s.hub.rotation.set(t*.2,t*.35,.15);s.parts.forEach((g,i)=>{const a=i*Math.PI/2+t*.27;g.position.set(Math.cos(a)*2.5,.65+Math.sin(a*2)*.35,Math.sin(a)*2.5);g.children[2].lookAt(s.g.worldToLocal(camera.position.clone()));});}
  if(s.index===4){s.parts.forEach((g,i)=>{g.scale.y=.22+Math.abs(Math.sin(t*1.5+i*.37))*1.7*Math.sin((i+1)/26*Math.PI);g.position.y=g.scale.y*.5-.15;});s.disk.rotation.z=t*.4;s.ring.rotation.z=-t*.25;}
  if(s.index===5){s.parts.forEach((g,i)=>{const ang=i*Math.PI/3+t*.25,returning=ease((local-2.2-i*.04)/1),radius=2.1*(1-returning);g.position.set(Math.cos(ang)*radius,.3+Math.sin(ang)*.8+returning*.8,Math.sin(ang)*radius*.6-returning*1.3);g.scale.setScalar(1-returning*.98);g.rotation.set(.1,Math.sin(t*.3)*.2,-.04);});s.bot.g.rotation.y=Math.sin(t*.5)*.35;}
  if(s.screen){const reveal=ease((local-.9)/.65)*(1-ease((local-3.05)/.55));s.screen.plane.material.opacity=reveal*(S?.8:.96);s.screen.g.visible=reveal>.001;s.screen.g.position.x=S?1.8:3.45;s.screen.g.position.y=1.8+(1-reveal)*.5;s.screen.g.rotation.set(-.045,-.25+(1-reveal)*.5,.015);}
 }
 trailDots.forEach((o,i)=>{o.position.copy(trailCurve.getPoint((t*.025+i/20)%1));});floatBits.forEach((o,i)=>{o.position.copy(o.userData.base);o.position.y+=Math.sin(t*.23+i)*.25;});
 floorTiles.forEach((o,i)=>{const u=i/99,p=trailCurve.getPoint(u);o.position.copy(p);o.position.y-=.6+Math.sin(t*.8+i*.3)*.09;o.rotation.y=Math.atan2(trailCurve.getTangent(u).x,trailCurve.getTangent(u).z);});
 const target=v(),eye=v();
 if(idx<0){const u=ease(t/2.7),angle=mix(-.45,.16,u);target.set(0,1.05,0);const d=P?12.6:S?10.2:9;eye.set(Math.sin(angle)*d,3.1+Math.sin(t*.5)*.3,Math.cos(angle)*d);if(P)target.y=2.1;}
 else if(idx<6){const age=t-starts[idx],trans=ease(age/.95),s=stations[idx],prev=idx===0?v(0,1.1,0):stations[idx-1].g.position.clone().add(v(0,.7,0));const current=s.g.position.clone().add(v(P?0:S?.4:1.3,.75,0));target.copy(prev).lerp(current,trans);const ang=(P?-.18:S?-.24:.12)+Math.sin(t*.28)*.23;const dist=P?14.9:S?12.8:11.5;eye.copy(target).add(v(Math.sin(ang)*dist,idx===0?5.3:P?3.1:3.8,Math.cos(ang)*dist));if(P)target.y+=.65;
 }else{const age=t-25.5,p=ease(age/2.2),from=stations[5].g.position.clone().add(v(0,.8,0));if(P){target.copy(from).lerp(v(0,16,0),p);eye.copy(target).add(v(mix(-2,18,p),mix(3,2,p),mix(15,43,p)));}else if(S){target.copy(from).lerp(v(0,1,0),p);eye.copy(target).add(v(mix(2,3,p),mix(4,16,p),mix(13,29,p)));}else{target.copy(from).lerp(v(0,1,0),p);eye.copy(target).add(v(mix(2,0,p),mix(4,20,p),mix(12,31,p)));}hero.visible=true;}
 camera.position.copy(eye);camera.lookAt(target);composer.render();
}
const marker=document.createElement('div');marker.style.cssText='position:absolute;left:0;top:0;width:2px;height:2px;z-index:9999';document.body.append(marker);
window.renderFrame=async t=>{update(t);const n=Math.round(t*30);marker.style.background=`rgb(${n&255},${16+(n>>8)},113)`;await new Promise(resolve=>requestAnimationFrame(resolve));composer.render();return{kind,t,width:W,height:H};};window.__ready=true;window.__renderInfo={three:T.REVISION,direction:'continuous camera flow',silent:true};update(0);
if(new URLSearchParams(location.search).has('play')){const start=performance.now();r.setAnimationLoop(()=>update(((performance.now()-start)/1000)%30));}
