import * as T from 'three';
import{RoomEnvironment}from'three/addons/environments/RoomEnvironment.js';
import{EffectComposer}from'three/addons/postprocessing/EffectComposer.js';
import{RenderPass}from'three/addons/postprocessing/RenderPass.js';
import{UnrealBloomPass}from'three/addons/postprocessing/UnrealBloomPass.js';
import{OutputPass}from'three/addons/postprocessing/OutputPass.js';
const kind=new URLSearchParams(location.search).get('kind')||'main',S=kind==='squares',P=kind==='constellation',W=innerWidth,H=innerHeight,theme=S?'square':P?'portrait':'wide';document.body.className=theme;
if(S)document.querySelector('.foot').textContent='SINCE 0.3.0 · SAMPLE PROJECT · DEVELOPMENT PREVIEW';
const scene=new T.Scene(),camera=new T.PerspectiveCamera(P?37:40,W/H,.1,100),renderer=new T.WebGLRenderer({alpha:false,antialias:true,preserveDrawingBuffer:true,powerPreference:'high-performance'});renderer.setPixelRatio(1);renderer.setSize(W,H);renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.0;document.body.prepend(renderer.domElement);
const pm=new T.PMREMGenerator(renderer),env=new RoomEnvironment();scene.environment=pm.fromScene(env,.1).texture;env.dispose();scene.environmentIntensity=.6;
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const bloom=new UnrealBloomPass(new T.Vector2(W,H),.13,.32,1.12);composer.addPass(bloom);composer.addPass(new OutputPass());
scene.add(new T.HemisphereLight(0xd6f2ff,S?0xa9b6cf:0x262438,1.8));for(const[c,i,p]of[[0xc5ffe7,1.5,[-5,7,8]],[0xb496f2,2,[6,3,-6]],[0xffffff,1,[1,10,1]]]){const l=new T.DirectionalLight(c,i);l.position.set(...p);scene.add(l);}
const bc=document.createElement('canvas');bc.width=1024;bc.height=Math.round(1024*H/W);const bx=bc.getContext('2d');bx.fillStyle=S?'#e8eff7':'#090d1b';bx.fillRect(0,0,bc.width,bc.height);for(const[x,y,rad,color]of S?[[.05,.8,.9,'#a6e1dd'],[1,.2,.8,'#d7c6f2'],[.4,0,.8,'#fffefd']]:[[.1,.9,.8,'#332b62'],[.95,.3,.8,'#124753'],[.7,1,.6,'#43284d']]){const g=bx.createRadialGradient(x*bc.width,y*bc.height,0,x*bc.width,y*bc.height,rad*Math.max(bc.width,bc.height));g.addColorStop(0,color);g.addColorStop(1,'transparent');bx.fillStyle=g;bx.fillRect(0,0,bc.width,bc.height);}scene.background=new T.CanvasTexture(bc);scene.background.colorSpace=T.SRGBColorSpace;
const clamp=x=>Math.max(0,Math.min(1,x)),ease=x=>{x=clamp(x);return x*x*x*(x*(x*6-15)+10);},out=x=>1-Math.pow(1-clamp(x),3),mix=T.MathUtils.lerp,rng=i=>{const n=Math.sin(i*127.1+78.2)*43758.5453;return n-Math.floor(n);},v=(x=0,y=0,z=0)=>new T.Vector3(x,y,z);
const world=new T.Group();scene.add(world);const dark=new T.MeshBasicMaterial({color:0x10243a});
const glow=c=>new T.MeshStandardMaterial({color:c,emissive:c,emissiveIntensity:.9,metalness:.12,roughness:.3});const mint=glow(0x9cf1cf),violet=glow(0xa396ed),cyan=glow(0x79cde5);
const colors=[0x86dac8,0x9aa5e4,0xb2a0d9,0x86c1e1,0xc4debf,0x92d5dd];
function sphere(radius,color,parent=world,metal=.22){const mat=new T.MeshPhysicalMaterial({color,metalness:metal,roughness:.3,clearcoat:.6,clearcoatRoughness:.2,iridescence:.38,iridescenceThicknessRange:[150,390]});const m=new T.Mesh(new T.SphereGeometry(radius,40,28),mat);parent.add(m);return m;}
function orb(radius,material,parent=world){const m=new T.Mesh(new T.SphereGeometry(radius,24,16),material);parent.add(m);return m;}
function torus(radius,width,material,parent=world){const m=new T.Mesh(new T.TorusGeometry(radius,width,8,90),material);parent.add(m);return m;}
function makeText(text,w,h,color='#d4f4f0'){const c=document.createElement('canvas');c.width=text==='M+'?256:1024;c.height=text==='M+'?128:240;const x=c.getContext('2d');x.font=`600 ${text==='M+'?92:80}px "Segoe UI",sans-serif`;x.textAlign='center';x.textBaseline='middle';x.fillStyle=color;x.fillText(text,c.width/2,c.height/2);const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;const m=new T.Mesh(new T.PlaneGeometry(w,h),new T.MeshBasicMaterial({map:tex,transparent:true,depthWrite:false,toneMapped:false}));return m;}
function beam(points,material=mint,parent=world,width=.018){const curve=new T.CatmullRomCurve3(points);const m=new T.Mesh(new T.TubeGeometry(curve,64,width,7,false),material);m.userData.curve=curve;parent.add(m);return m;}
const hero=new T.Group();world.add(hero);const heroBody=sphere(.76,0x98a3da,hero,.28);const eyes=[];for(const x of[-.245,.245]){const eye=orb(.065,dark,hero);eye.position.set(x,.105,.714);eye.scale.y=1.1;eyes.push(eye);}const mouth=new T.Mesh(new T.TubeGeometry(new T.CatmullRomCurve3([v(-.23,-.25,.73),v(0,-.12,.757),v(.23,-.25,.73)]),28,.026,7,false),dark);hero.add(mouth);
const brows=[];for(const side of[-1,1]){const br=beam([v(side*.35,.24,.67),v(side*.25,.29,.69),v(side*.16,.3,.7)],dark,hero,.018);brows.push(br);}
const blush=[];for(const side of[-1,1]){const m=orb(.08,new T.MeshBasicMaterial({color:0xeeb7d2,transparent:true,opacity:0}),hero);m.scale.set(1.2,.46,.15);m.position.set(side*.38,-.04,.66);blush.push(m);}
const mefi=new T.Group();world.add(mefi);const mefiBody=sphere(.48,0xcbffe6,mefi,.7);mefiBody.material.iridescence=1;const logo=makeText('M+',.78,.36,'#153546');logo.position.z=.51;mefi.add(logo);const mefiName=makeText('Mefi Studio',2,.4);mefiName.position.set(0,-.88,.15);mefi.add(mefiName);const mefiRings=[torus(.67,.016,mint,mefi),torus(.8,.009,violet,mefi)];mefiRings[0].rotation.set(.55,.2,.2);mefiRings[1].rotation.set(.1,1,.4);
const nodes=[],N=12;for(let i=0;i<N;i++){const group=new T.Group();world.add(group);const body=sphere(.23+(i<3?.065:0),colors[i%6],group,.3);const shine=orb(.038,new T.MeshBasicMaterial({color:0xe4fff6}),group);shine.position.set(-.055,.07,.22);const ring=torus(i<3?.39:.31,.009,i%2?violet:cyan,group);ring.rotation.x=.3;ring.visible=false;nodes.push({group,body,ring,radius:i<3?.295:.23});}
// Resolve collisions at fixed time steps, so every export tells the same story.
const bodies=nodes.map((n,i)=>({x:-2.6+rng(i)*5.2,y:-2.1+rng(i+30)*2.2,vx:(rng(i+60)-.5)*3.6,vy:(rng(i+90)-.5)*3.4,r:n.radius,hit:0})),history=[];
for(let f=0;f<=420;f++){for(const a of bodies){a.x+=a.vx/30;a.y+=a.vy/30;a.hit*=.7;if(Math.abs(a.x)>2.8-a.r){a.x=Math.sign(a.x)*(2.8-a.r);a.vx*=-1;a.hit=1;}if(a.y<-2.1+a.r||a.y>.4-a.r){a.y=T.MathUtils.clamp(a.y,-2.1+a.r,.4-a.r);a.vy*=-1;a.hit=1;}}
 for(let i=0;i<N;i++)for(let j=i+1;j<N;j++){const a=bodies[i],b=bodies[j],dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy),min=a.r+b.r+.015;if(d<min){const nx=dx/(d||.001),ny=dy/(d||.001),over=(min-d)/2;a.x-=nx*over;a.y-=ny*over;b.x+=nx*over;b.y+=ny*over;const rel=(a.vx-b.vx)*nx+(a.vy-b.vy)*ny;if(rel>0){a.vx-=rel*nx;a.vy-=rel*ny;b.vx+=rel*nx;b.vy+=rel*ny;}a.hit=b.hit=1;}}
 history.push(bodies.map(a=>({x:a.x,y:a.y,hit:a.hit})));}
const tree=[[-2,-.65,0],[0,-.65,.35],[2,-.65,0],[-2.65,-2.05,.1],[-1.35,-2.05,-.15],[-.6,-2.05,.28],[.6,-2.05,-.22],[1.35,-2.05,.15],[2.65,-2.05,-.15],[-2.1,-3.1,.2],[0,-3.1,-.1],[2.1,-3.1,.1]].map(p=>v(...p));
const parents=[-1,-1,-1,0,0,1,1,2,2,4,6,7];const lines=[],packets=[],ripples=[];
for(let i=0;i<N;i++){const from=i<3?v(0,.8,0):tree[parents[i]],to=tree[i],mid=from.clone().lerp(to,.5);mid.z+=.45;const l=beam([from,mid,to],i%3===1?violet:cyan);lines.push(l);packets.push(orb(.048,i%2?mint:violet));const ripple=torus(nodes[i].radius+.09,.01,new T.MeshBasicMaterial({color:0xe6a1bb,transparent:true,opacity:0}));ripples.push(ripple);}
const rootLine=beam([v(0,2.1,0),v(0,1.5,.25),v(0,.8,0)],mint);
for(const l of[...lines,rootLine]){l.material=l.material.clone();l.material.transparent=true;l.material.depthWrite=false;}
const overviewTargets=nodes.map((n,i)=>{const angle=-Math.PI/2+i*Math.PI/6;return v(Math.cos(angle)*3,Math.sin(angle)*2+.4,Math.sin(angle*2)*.4);});
const overviewLines=overviewTargets.map((to,i)=>{const l=beam([v(0,1.8,0),v(to.x*.45,(1.8+to.y)/2,-.45),to],i%2?cyan:violet);l.material=l.material.clone();l.material.transparent=true;l.material.depthWrite=false;l.visible=S;return l;});
const labels=[];const names=['PLAN','BUILD','VERIFY','Project map','Playbook','Providers','Media','Reports','Review'];for(let i=0;i<9;i++){const text=makeText(names[i],i<3?1.5:1.62,.35,S?'#315571':'#b6d9df');world.add(text);labels.push(text);}
// Soft volumetric shaft and falling particles announce Mefi without sound.
const beamCanvas=document.createElement('canvas');beamCanvas.width=256;beamCanvas.height=1024;const beamCtx=beamCanvas.getContext('2d');const beamG=beamCtx.createLinearGradient(0,0,256,0);beamG.addColorStop(0,'transparent');beamG.addColorStop(.35,'#b8ffe922');beamG.addColorStop(.5,'#eafffaaa');beamG.addColorStop(.65,'#b8ffe922');beamG.addColorStop(1,'transparent');beamCtx.fillStyle=beamG;beamCtx.fillRect(0,0,256,1024);beamCtx.globalCompositeOperation='destination-in';const beamFade=beamCtx.createLinearGradient(0,0,0,1024);beamFade.addColorStop(0,'transparent');beamFade.addColorStop(.15,'white');beamFade.addColorStop(.75,'white');beamFade.addColorStop(1,'transparent');beamCtx.fillStyle=beamFade;beamCtx.fillRect(0,0,256,1024);const beamTex=new T.CanvasTexture(beamCanvas);const shaft=new T.Mesh(new T.PlaneGeometry(3.7,12),new T.MeshBasicMaterial({map:beamTex,transparent:true,opacity:0,depthWrite:false,blending:T.AdditiveBlending}));world.add(shaft);shaft.position.set(1.6,5.1,-1);
const portal=torus(.85,.026,mint);portal.rotation.x=Math.PI/2;portal.position.set(1.6,4.8,0);const drops=[];for(let i=0;i<40;i++){const d=orb(.012+rng(i)*.023,i%3?violet:mint);drops.push(d);}
const dust=[];for(let i=0;i<55;i++){const d=orb(.008+rng(i+30)*.017,i%3?cyan:violet);d.userData.base=v((rng(i+100)-.5)*17,(rng(i+200)-.5)*13,-4-rng(i+300)*7);dust.push(d);}
const featureData=[['map','See the whole project.','HOME · PLANS · PROJECT MAP'],['pipeline','Watch agents work together.','AGENT BRAIN · LIVE PIPELINES'],['playbook','Keep what worked.','PLAYBOOK · BRAIN MAPS'],['routing','Bring your favorite models.','OPENROUTER · ROUTING · USAGE'],['music','Stay in your flow.','MUSIC · RADIO · FLOATING VIDEO'],['tasks','Know what’s really done.','REVIEWS · REPORTS · CHECKS']];
const screens=[];
if(S)for(const[key]of featureData){const im=await new Promise((resolve,reject)=>{const q=new Image();q.onload=()=>resolve(q);q.onerror=reject;q.src=`../../dist/promo/screens/${key}.png`;});const tex=new T.Texture(im);tex.needsUpdate=true;tex.colorSpace=T.SRGBColorSpace;tex.anisotropy=renderer.capabilities.getMaxAnisotropy();const screen=new T.Mesh(new T.PlaneGeometry(5.7,3.56),new T.MeshBasicMaterial({map:tex,transparent:true,opacity:0,toneMapped:false}));world.add(screen);screen.visible=false;screens.push(screen);}
const caption=document.querySelector('.caption'),title=document.querySelector('h1'),sub=document.querySelector('.sub'),url=document.querySelector('.url');let textKey='';
function text(state,heading,subtitle='',address='',opacity=1){const key=state+heading;if(key!==textKey){textKey=key;document.body.className=theme+(state==='end'?' end':'');title.innerHTML=heading;sub.textContent=subtitle;url.textContent=address;}caption.style.opacity=String(opacity);caption.style.transform=`translateY(${(1-opacity)*14}px)`;}
function expression(smile,t,gaze){eyes.forEach((e,i)=>{e.position.x=(i?1:-1)*.245+gaze.x*.045;e.position.y=.105+gaze.y*.07;let blink=1;for(const at of[2.2,5.7,10.6,17.3,23,29])blink*=1-.93*Math.exp(-Math.pow((t-at)/.08,2));e.scale.y=(.65+smile*.55)*blink;});mouth.geometry.dispose();mouth.geometry=new T.TubeGeometry(new T.CatmullRomCurve3([v(-.23,-.23,.73),v(0,mix(-.1,-.36,smile),.757),v(.23,-.23,.73)]),24,.024,6,false);brows.forEach((b,i)=>{b.visible=smile<.65;b.rotation.z=(i?1:-1)*smile*.25;});blush.forEach(b=>b.material.opacity=smile*.7);heroBody.material.color.set(0x919dcc).lerp(new T.Color(0x97e4d0),smile);}
function story(t){const organized=ease((t-12)/5.4),holy=out((t-7)/.9)*(1-ease((t-13)/2)),happy=ease((t-10.9)/3.7),end=ease((t-25.3)/1.5);expression(happy,t,v(t>7?.8:0,t>7&&t<10?.8:-.8));
 let heroPos=v(0,1.8,0);if(t>9.7&&t<12){const a=ease((t-9.7)/2.3);heroPos.lerp(v(.63,1.13,.05),a);heroPos.y+=Math.sin(a*Math.PI)*.28;}if(t>=12)heroPos.set(.63*(1-ease((t-12)/2)),mix(1.13,.8,ease((t-12)/2)),0);
 if(t>=25.3){const to=P?v(0,-.1,0):v(2.55,.2,.2);heroPos.lerp(to,end);}hero.position.copy(heroPos);hero.position.y+=Math.sin(t*1.5)*.045;hero.rotation.set(t<8?.13:0,t>=25.3?ease((t-25.9)/2.5)*Math.PI*2:Math.sin(t*.55)*.08,-.035*Math.sin(t));hero.scale.setScalar(t>=25.3?mix(1,1.5,end):1);
 const fall=ease((t-7.3)/2.8),gather=ease((t-12)/2);mefi.visible=t>7&&end<.95;mefiName.material.opacity=1-ease((t-12)/1.2);mefi.position.set(mix(1.6,0,gather),mix(6.5,1.15,fall)*(1-gather)+2.1*gather,0);mefi.scale.setScalar((1-end*.9)*out((t-7)/.5));mefiRings[0].rotation.z=t*.2;mefiRings[1].rotation.z=-t*.25;
 shaft.material.opacity=holy*.65;shaft.rotation.y=camera.position.x*.012;portal.visible=holy>.02;portal.scale.setScalar(.8+holy*.45);portal.material.emissiveIntensity=.8+holy*.7;
 drops.forEach((d,i)=>{d.visible=holy>.01;d.position.set(1.6+(rng(i+900)-.5)*1.8,6.4-((t*.85+i*.17)%7),-.35+(rng(i+500)-.5)*.6);d.scale.setScalar(holy);});
 const frame=history[Math.min(420,Math.floor(Math.min(t,12)*30))];for(let i=0;i<N;i++){const node=nodes[i],row=i<3?0:i<9?1:2,p=ease((t-12.3-row*.9-i*.08)/1.9),q=frame[i],initial=v(q.x,q.y,.05*Math.sin(t+i));node.group.position.copy(initial).lerp(tree[i],p);node.group.position.y+=Math.sin(t*1.1+i)*.035*p;node.group.scale.set(1+q.hit*.14*(1-p),1-q.hit*.12*(1-p),1);node.group.rotation.y=t*.08;node.body.material.color.set(0xb2a0b8).lerp(new T.Color(colors[i%6]),p);node.body.material.emissive.set(colors[i%6]);node.body.material.emissiveIntensity=.05+p*.2;node.ring.visible=p>.8;node.ring.rotation.z=t*.2+i;node.group.scale.multiplyScalar(1-end*.95);
  const grow=ease((t-12.9-row*.9-i*.08)/1.45);lines[i].visible=grow>0&&end<.97;lines[i].geometry.setDrawRange(0,Math.floor(lines[i].geometry.index.count*grow/6)*6);lines[i].material.opacity=1-end;packets[i].visible=grow>.99&&end<.9;packets[i].position.copy(lines[i].userData.curve.getPoint((t*.37+i*.14)%1));packets[i].scale.setScalar(1-end);
  ripples[i].position.copy(node.group.position);ripples[i].position.z+=.35;ripples[i].material.opacity=q.hit*.38*(1-p);ripples[i].scale.setScalar(1+(1-q.hit)*.85);
 }
 rootLine.visible=t>12.1&&end<.9;rootLine.material.opacity=1-end;rootLine.geometry.setDrawRange(0,Math.floor(rootLine.geometry.index.count*ease((t-12.1)/1)/6)*6);
 labels.forEach((l,i)=>{l.position.copy(tree[i]);l.position.y-=i<3?.5:.41;l.position.z+=.4;l.material.opacity=ease((t-17-i*.16)/1)*(1-end);l.visible=l.material.opacity>.01;});
 if(t<25.3){text('story','','','',0);if(t>19&&t<22.2)text('connected','Everything, connected.','','',out((t-19)/.5)*(1-ease((t-21.7)/.5)));}else text('end','Mefi’s Studio AI+','Your idea. A whole studio.','github.com/nateecho32-stack/mefi-studio',out((t-26)/.65));
 const target=v(0,-.2,0),eye=v();if(P){target.y=mix(.25,-.2,ease(t/3));const distance=t<2.5?mix(12.5,18,ease(t/2.5)):18;eye.set(Math.sin(t*.15)*1.3,1,distance);if(t>25.3){target.y=mix(-.2,1.4,end);eye.set(0,1.5,16);}}else{const intro=ease(t/2.6);target.set(0,mix(1.5,-.3,intro),0);let dx=mix(-1.4,1.5,ease((t-7)/5)),dy=mix(1.5,2.5,ease((t-15)/6)),dz=mix(6.6,11.8,intro);if(t>15)dx=1.5+Math.sin((t-15)*.25)*1.45;if(t>22)dx=mix(dx,-1.8,ease((t-22)/3));if(t>25.3){target.lerp(v(.2,.3,0),end);dx=mix(dx,0,end);dy=mix(dy,.6,end);dz=mix(dz,10.5,end);}eye.set(dx,dy,dz);}camera.position.copy(eye);camera.lookAt(target);
}
function overview(t){const idx=t<3?-1:t<26?Math.min(5,Math.floor((t-3)/(23/6))):6,age=idx<0?t:idx===6?t-26:t-(3+idx*23/6),end=idx===6?ease(age/1.4):0;expression(.85,t,v(Math.sin(t*.4),.15));hero.position.set(0,1.8+Math.sin(t)*.05,0);hero.rotation.set(0,idx===6?ease((age-.7)/2.2)*Math.PI*2:Math.sin(t*.3)*.14,0);hero.scale.setScalar(idx===6?1.5:1);mefi.visible=false;shaft.visible=false;portal.visible=false;rootLine.visible=false;drops.forEach(d=>d.visible=false);labels.forEach(l=>l.visible=false);
 const targets=overviewTargets;overviewLines.forEach((l,i)=>{const active=idx>=0&&idx<6&&(i===idx*2||i===idx*2+1);l.material.opacity=(active?.9:.27)*(1-end);l.geometry.setDrawRange(0,Math.floor(l.geometry.index.count*out((t-.6-i*.07)/1.2)/6)*6);l.visible=end<.98;});
 for(let i=0;i<N;i++){const node=nodes[i],active=idx>=0&&idx<6&&(i===idx*2||i===idx*2+1),p=out((t-.5-i*.07)/1.2);node.group.position.copy(targets[i]).multiplyScalar(p);node.group.position.y+=Math.sin(t*1.1+i)*.09;node.group.scale.setScalar((active?1.15:.8)*(1-end*.8));node.body.material.color.set(colors[i%6]);node.body.material.emissiveIntensity=active?.28:.03;node.ring.visible=active;node.ring.rotation.set(.4,t*.6,.2);ripples[i].material.opacity=0;lines[i].visible=false;packets[i].visible=false;}
 screens.forEach((s,i)=>{const p=i===idx?ease((age-.5)/.65)*(1-ease((age-3.27)/.48)):0;s.visible=p>.001;s.material.opacity=p;s.position.set(0,-.18+(1-p)*.5,.6);s.rotation.set(-.07,.12*Math.sin(t*.3)+(1-p)*.3,0);s.scale.setScalar(.85+.12*p);});
 if(idx<0)text('intro','One studio.<br>Connected work.','WHAT’S NEW SINCE 0.3.0','',out(t/.7)*(1-ease((t-2.5)/.5)));else if(idx<6)text('feature',featureData[idx][1],featureData[idx][2],'',out((age-.4)/.5)*(1-ease((age-3.3)/.45)));else text('end','Mefi’s Studio AI+','Bring an idea. Make it real.','github.com/nateecho32-stack/mefi-studio',out((age-.6)/.7));
 camera.position.set(Math.sin(t*.23)*1.3,1.25,12.8);camera.lookAt(0,idx===6?1:.1,0);if(idx===6)hero.position.y=2.05;
}
function ballet(t){const intro=ease(t/3),build=ease((t-4)/16),end=ease((t-25.1)/1.5);expression(.75+.25*build,t,v(Math.sin(t),Math.cos(t*.3)));hero.position.set(Math.sin(t*.4)*.2,2.55+.12*Math.sin(t),0);hero.rotation.set(.03*Math.sin(t),t>25?ease((t-25.7)/2.5)*Math.PI*2:Math.sin(t*.5)*.2,Math.sin(t*.35)*.07);hero.scale.setScalar(mix(1.3,1.65,end));if(end>0)hero.position.y=mix(2.55,-.2,end);
 mefi.visible=false;shaft.visible=false;portal.visible=false;rootLine.visible=t>4&&end<.95;rootLine.material.opacity=ease((t-4)/1)*(1-end);rootLine.geometry.setDrawRange(0,rootLine.geometry.index.count);drops.forEach(d=>d.visible=false);labels.forEach(l=>l.visible=false);
 for(let i=0;i<N;i++){const group=nodes[i].group,level=Math.floor(i/2),a=t*.36+i*Math.PI,sp=Math.sin(t*1.8+level*.6),connected=ease((t-3.5-i*.72)/1.35),target=tree[i].clone();const chaos=v(Math.cos(a)*(1.1+.7*intro),1.2-level*.53+sp*.16,Math.sin(a)*1.4);group.position.copy(chaos).lerp(target,connected);group.position.y+=Math.sin(t*.7+i)*.04*connected;group.scale.setScalar((1+.12*Math.max(0,Math.cos(t*2+i))*(1-connected))*(1-end*.95));nodes[i].body.material.color.set(colors[i%6]);nodes[i].body.material.emissiveIntensity=.12+connected*.14;nodes[i].ring.visible=connected>.8;nodes[i].ring.rotation.set(.4,.1,t*.3+i);ripples[i].position.copy(group.position);ripples[i].position.z+=.3;ripples[i].material.opacity=(1-connected)*.25*Math.max(0,Math.cos(t*2+i));
 const grow=ease((t-4-i*.72)/1.4);lines[i].visible=grow>.01&&end<.95;lines[i].geometry.setDrawRange(0,Math.floor(lines[i].geometry.index.count*grow/6)*6);packets[i].visible=grow>.98&&end<.9;packets[i].position.copy(lines[i].userData.curve.getPoint((t*.42+i*.12)%1));}
 if(t<4)text('ballet','Ideas meet.','AND SOMETHING STARTS.','',out(t/.7)*(1-ease((t-3.5)/.5)));else if(t<10.3)text('ballet','They find a rhythm.','','',out((t-4.8)/.8)*(1-ease((t-9.7)/.6)));else if(t<16.8)text('ballet','A path takes shape.','PLAN · BUILD · VERIFY','',out((t-11)/.8)*(1-ease((t-16.2)/.6)));else if(t<25.1)text('ballet','Everything comes together.','PROJECT MAPS · AGENT BRAIN · PLAYBOOK','',out((t-18)/.9)*(1-ease((t-24.4)/.7)));else text('end','Mefi’s Studio AI+','Your idea. A whole studio.','github.com/nateecho32-stack/mefi-studio',out((t-25.7)/.7));
 const angle=.24*Math.sin(t*.22);camera.position.set(Math.sin(angle)*17,1.1+Math.sin(t*.25)*.5,Math.cos(angle)*17);camera.lookAt(0,mix(-.15,1.65,end),0);
}
function update(t){if(S)overview(t);else if(P)ballet(t);else story(t);dust.forEach((d,i)=>{d.position.copy(d.userData.base);d.position.y+=Math.sin(t*.3+i)*.14;d.visible=!S;});composer.render();}
const marker=document.createElement('div');marker.style.cssText='position:absolute;left:0;top:0;width:2px;height:2px;z-index:9999';document.body.append(marker);
window.renderFrame=async t=>{update(t);const n=Math.round(t*30);marker.style.background=`rgb(${n&255},${16+(n>>8)},113)`;await new Promise(resolve=>requestAnimationFrame(resolve));composer.render();return{t,kind,width:W,height:H};};window.__ready=true;window.__renderInfo={three:T.REVISION,direction:'circles that bump, connect and grow',silent:true};update(0);
if(new URLSearchParams(location.search).has('play')){const start=performance.now();renderer.setAnimationLoop(()=>update(((performance.now()-start)/1000)%30));}
